title: Localisation and Telemetry under Bluetooth Mesh
logo:
description: An IoT project for the Internet of Things course at the University of Salento
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal